# Generated by Django 5.1.1 on 2025-01-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinmoi_app', '0002_preferensipengguna'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='harga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='kategori',
            field=models.CharField(blank=True, choices=[('main_course', 'Main Course'), ('side_dish', 'Side Dish'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='tipe_rasa',
            field=models.CharField(blank=True, choices=[('manis', 'Manis'), ('asin', 'Asin'), ('pedas', 'Pedas')], max_length=100, null=True),
        ),
    ]
