# Generated by Django 5.1.4 on 2025-02-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinmoi_app', '0006_menu_harga_alter_menu_kategori_alter_menu_tipe_rasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='gambar',
            field=models.ImageField(upload_to='media/menu_images/'),
        ),
    ]
