# Generated by Django 5.1.4 on 2025-02-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinmoi_app', '0007_alter_menu_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='gambar',
            field=models.ImageField(upload_to='menu_images/'),
        ),
    ]
