# Generated by Django 5.1.4 on 2025-02-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinmoi_app', '0008_alter_menu_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='kategori',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('beverage', 'Beverage'), ('congee', 'Congee'), ('dessert', 'Dessert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tipe_rasa',
            field=models.CharField(choices=[('manis', 'Manis'), ('gurih', 'Gurih'), ('pedas', 'Pedas')], max_length=50),
        ),
    ]
