# Generated by Django 5.1.4 on 2025-02-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinmoi_app', '0009_alter_menu_harga_alter_menu_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='harga',
        ),
        migrations.AlterField(
            model_name='menu',
            name='kategori',
            field=models.CharField(blank=True, choices=[('appetizer', 'Appetizer'), ('beverage', 'Beverage'), ('congee', 'Congee'), ('dessert', 'Dessert')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tipe_rasa',
            field=models.CharField(blank=True, choices=[('manis', 'Manis'), ('gurih', 'Gurih'), ('pedas', 'Pedas')], max_length=100, null=True),
        ),
    ]
