# Generated by Django 5.1.1 on 2025-02-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinmoi_app', '0011_menu_harga_alter_menu_kategori_alter_menu_tipe_rasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='kategori',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Beverage', 'Beverage'), ('Congee', 'Congee'), ('Dessert', 'Dessert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nama',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tipe_rasa',
            field=models.CharField(choices=[('Manis', 'Manis'), ('Gurih', 'Gurih'), ('Pedas', 'Pedas')], max_length=50),
        ),
    ]
